#!/usr/bin/env python3
"""Generate src/ai_selftest_vectors.h for CONFIG_SA_AI_SELF_TEST.

Runs each known 24h window through the INT8 .tflite on the host, using the
exact same preprocessing as src/ai_inference.cpp (z-score with the contract
mean/std, INT8 quantization, softmax over the dequantized logits), and writes
the window plus the expected signal/p_alert into a C header. The device then
has to reproduce these numbers (within AI_SELFTEST_P_TOLERANCE).

Input: a .npy file of shape (N, 24, 4), raw units, channel order
[Temperature, Humidity, CO, NO2], CO/NO2 in ug/m3, t=0 oldest hour.

Usage (needs `pip install numpy tensorflow` or `ai-edge-litert`):
    python gen_selftest_vectors.py windows.npy \
        [--names names.txt] [--expected-p p_alert.npy] [--out ../src/ai_selftest_vectors.h]

--expected-p: optional (N,) p_alert from Hung's reference pipeline. When
given, the script prints the host-vs-reference difference for each window,
so a mismatch is caught before flashing. The header always stores the host
TFLite result, which is what the device must match.
"""

import argparse
import json
import pathlib

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
MODEL = HERE.parent / "model" / "model_beijing_freeze_int8.tflite"
CONTRACT = HERE.parent / "model" / "model_contract_freeze.json"
DEFAULT_OUT = HERE.parent / "src" / "ai_selftest_vectors.h"


def load_interpreter(path):
    try:
        from ai_edge_litert.interpreter import Interpreter
    except ImportError:
        from tensorflow.lite.python.interpreter import Interpreter
    interp = Interpreter(model_path=str(path))
    interp.allocate_tensors()
    return interp


def find_logits(interp):
    for out in interp.get_output_details():
        if out["shape"][-1] == 2:
            return out
    raise RuntimeError("no 2-class output in model")


def infer(interp, window, mean, std):
    """window: (24, 4) raw -> p_alert, same math as ai_inference.cpp."""
    inp = interp.get_input_details()[0]
    scale, zero = inp["quantization"]
    norm = (window - mean) / std  # (24, 4), matches runtime layout t*4 + c
    q = np.clip(np.round(norm / scale) + zero, -128, 127).astype(np.int8)
    interp.set_tensor(inp["index"], q.reshape(inp["shape"]))
    interp.invoke()
    out = find_logits(interp)
    o_scale, o_zero = out["quantization"]
    raw = (interp.get_tensor(out["index"]).reshape(-1)[:2].astype(np.float32) - o_zero) * o_scale
    e = np.exp(raw - raw.max())
    return float(e[1] / e.sum())


def c_float(x):
    return f"{x:.6f}f"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("windows", help=".npy of shape (N, 24, 4)")
    ap.add_argument("--names", help="text file, one name per window")
    ap.add_argument("--expected-p", help=".npy of shape (N,) with reference p_alert")
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    windows = np.load(args.windows).astype(np.float32)
    if windows.ndim != 3 or windows.shape[1:] != (24, 4):
        raise SystemExit(f"expected (N, 24, 4), got {windows.shape}")
    names = (pathlib.Path(args.names).read_text(encoding="utf-8").split("\n") if args.names else [])
    names = [n.strip() for n in names if n.strip()]
    if names and len(names) != len(windows):
        raise SystemExit("--names count does not match number of windows")
    names = names or [f"window_{i}" for i in range(len(windows))]
    ref = np.load(args.expected_p).reshape(-1) if args.expected_p else None

    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    mean = np.array(contract["mean"], dtype=np.float32)
    std = np.array(contract["std"], dtype=np.float32)
    interp = load_interpreter(MODEL)

    entries = []
    for i, (name, w) in enumerate(zip(names, windows)):
        p = infer(interp, w, mean, std)
        sig = int(p > 0.5)
        msg = f"{name}: signal={sig} p_alert={p:.4f}"
        if ref is not None:
            msg += f" ref={ref[i]:.4f} diff={abs(p - ref[i]):.4f} ref_signal={int(ref[i] > 0.5)}"
        print(msg)

        # Header stores window[channel][t] (see ai_input_get_window()).
        rows = ",\n".join("            {" + ", ".join(c_float(v) for v in w[:, c]) + "}" for c in range(4))
        entries.append(
            f'    {{\n        .name = "{name}",\n        .window = {{\n{rows},\n        }},\n'
            f"        .expected_signal = {sig},\n        .expected_p_alert = {c_float(p)},\n    }},"
        )

    header = f"""/**
 * @file ai_selftest_vectors.h
 *
 * @brief Known input windows + expected model output for CONFIG_SA_AI_SELF_TEST.
 *
 * GENERATED by tools/gen_selftest_vectors.py -- do not edit by hand.
 *
 * Copyright (C) 2026 MinhNhat & BaoViet
 */

#pragma once

#include "ai_input.h"

#include <stddef.h>

typedef struct {{
    const char *name;
    float window[AI_INPUT_NUM_CHANNELS][AI_INPUT_WINDOW_LEN]; /* raw units, CO/NO2 in ug/m3 */
    int expected_signal;                                       /* 0 = safe, 1 = alert */
    float expected_p_alert;                                    /* softmax probability of class 1 */
}} ai_selftest_vector_t;

/* Allowed |p_alert(device) - p_alert(expected)|. */
#define AI_SELFTEST_P_TOLERANCE 0.02f

#define AI_SELFTEST_VECTOR_COUNT {len(entries)}

static const ai_selftest_vector_t k_ai_selftest_vectors[AI_SELFTEST_VECTOR_COUNT] = {{
{chr(10).join(entries)}
}};
"""
    pathlib.Path(args.out).write_text(header, encoding="utf-8", newline="\n")
    print(f"wrote {len(entries)} vector(s) to {args.out}")


if __name__ == "__main__":
    main()
